### ISSUE TITLE
Support a literate coding view

### ISSUE THREAD

**Issue by indexzero** [rrrene/inch#27]
Since you're already parsing all the documentation it would be really easy to build a table of contents to a really slick literate coding view of the source itself. Something similar to docco: https://github.com/jashkenas/docco

**Comment by rrrene** [comment]
I actually thought about something like this since day one: To enable people to browse code documentation next to an indicator where they could add some more ... your suggestion goes into a simliar direction.

While the goal for v1.0.0 is to get the evaluation working correctly and providing a good user experience in Ruby and JS, this is something that could be really cool  :+1:

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.

**Comment by indexzero** [comment]
No apologies needed. Open source is a labor of love ❤️
