### ISSUE TITLE
add way to parse the rdoc/yard documentation in C/C++ code

### ISSUE THREAD

**Issue by Hanmac** [rrrene/inch#29]
i already did report it there https://github.com/inch-ci/inch_ci-web/issues/76 but i think it might be more correct in this one.

i write C(++) extensions like https://github.com/Hanmac/rwx in them there i document my code using rdoc comments.

Inch currently doesnt know what to do with them ... 
but Rdoc and yard can parse my code and understand (mostly) the documented methods and attributes, so i think this feature might be added in Inch too

**Comment by rrrene** [comment]
Oh yeah, sorry for not replying. I will close the other ticket and keep this one open.

I can't make any predictions when this might land in Inch, since I don't write C extensions and will have to look up how YARD parses them and if I can take that output ...

I would however accept a PR on this one.

**Comment by Hanmac** [comment]
ok i might have been wrong, its mostly Rdoc that does support C(++) files and not so much yard ... 
i didnt know which one, but i did thought that i fixed it in one of my project so that could support both

hm ok it seems that YARD still has problems with my code: https://github.com/lsegal/yard/issues/809
and probably other problems

**Comment by rrrene** [comment]
I apologize for the age/inactivity on this issue. I should have done a better job at resolving this properly. 😥 

Please feel free to re-open this issue at your discretion.
