### ISSUE TITLE
Problem with branches

### ISSUE THREAD

**Issue by pprzetacznik** [rrrene/inch#34]
When I evaluate "pprzetacznik/IElixir" project on this site: http://inch-ci.org, I can see some tips about how I can configure project to make it work with Inch CI.

On the right there's a switch with "branch: master" and when I change branch to "feature/inch-ci" I see error page with following message:

```
The page you were looking for doesn't exist.

You may have mistyped the address or the page may have moved.

If you are the application owner check the logs for more information.
```

http://inch-ci.org/github/pprzetacznik/IElixir/branch/feature/inch-ci

**Comment by pprzetacznik** [comment]
@rrrene Hi! I would like to ask you about this issue: https://github.com/inch-ci/inch_ci-web/commit/9bd9653fa1011ef6991a95b4b7f80e97434e4eb4

Because now I get an error:
```
We're sorry, but something went wrong.

If you are the application owner check the logs for more information.
```

Would you mind to take a look on that?

**Comment by rrrene** [comment]
Hi,

the "problem" is the slash in the branch name. I coded up a quick fix on the weekend, which worked on my machine but not on the server.

Unfortunately, I don't have time to look into it right now due to an upcoming business trip. I will try to in the future, since I want to support branches with slashes in their names, but right now my schedule is too tight to figure out why the commit you referenced does not work in production.

**Suggestion:** If you just want to test your repo, create a temporary branch without a slash (e.g. "tmp-inch-ci") and use the `mix inchci.add` task to create a report on Inch CI. After deciding whether or not you want to keep the Inch CI integration, you can merge it into master and delete the "tmp-..." branch.
