### ISSUE TITLE
Update Inch to user a newer YARD

### ISSUE THREAD

**Issue by jashank** [rrrene/inch#42]
yard-0.8.7.5 uses a deprecated method in Rake, and with the release of Rake 12, that method (`Rake::TaskManager#last_comment`) is gone for good.  Is there any particular reason to pin an older version of yard?

**Comment by rrrene** [comment]
Oh yeah, we should update that. 👍 

It's not working out-of-the-box though, I'll have to investigate how YARD's API has changed:

```
/home/rene/.rvm/gems/ruby-2.1.6@inch/gems/yard-0.9.5/lib/yard/code_objects/base.rb:364:in `method_missing': undefined method `meths' for #<yardoc constant CONFIG> (NoMethodError)
	from /home/rene/.rvm/gems/ruby-2.1.6@inch/gems/yard-0.9.5/lib/yard/code_objects/proxy.rb:194:in `method_missing'
	from /home/rene/.rvm/gems/ruby-2.1.6@inch/gems/yard-0.9.5/lib/yard/code_objects/method_object.rb:137:in `overridden_method'
	from /home/rene/projects/inch/lib/inch/language/ruby/provider/yard/object/method_object.rb:62:in `overridden?'
	from /home/rene/projects/inch/lib/inch/code_object/converter.rb:75:in `public_send'
	from /home/rene/projects/inch/lib/inch/code_object/converter.rb:75:in `block in to_hash'
	from /home/rene/projects/inch/lib/inch/code_object/converter.rb:73:in `each'
	from /home/rene/projects/inch/lib/inch/code_object/converter.rb:73:in `to_hash'
	from /home/rene/projects/inch/lib/inch/code_object/proxy.rb:14:in `for'
	from /home/rene/projects/inch/lib/inch/codebase/object.rb:32:in `initialize'
	from /home/rene/projects/inch/lib/inch/codebase/objects.rb:19:in `new'
	from /home/rene/projects/inch/lib/inch/codebase/objects.rb:19:in `block in initialize'
	from /home/rene/projects/inch/lib/inch/codebase/objects.rb:18:in `map'
	from /home/rene/projects/inch/lib/inch/codebase/objects.rb:18:in `initialize'
	from /home/rene/projects/inch/lib/inch/codebase/proxy.rb:7:in `new'
	from /home/rene/projects/inch/lib/inch/codebase/proxy.rb:7:in `initialize'
	from /home/rene/projects/inch/lib/inch/codebase/proxy.rb:12:in `new'
	from /home/rene/projects/inch/lib/inch/codebase/proxy.rb:12:in `parse'
	from /home/rene/projects/inch/lib/inch/codebase.rb:12:in `parse'
	from /home/rene/projects/inch/lib/inch/cli/command/base_list.rb:24:in `prepare_codebase'
	from /home/rene/projects/inch/lib/inch/cli/command/suggest.rb:26:in `run'
	from /home/rene/projects/inch/lib/inch/cli/command/base.rb:52:in `run'
	from /home/rene/projects/inch/lib/inch/cli/command_parser.rb:100:in `run_command'
	from /home/rene/projects/inch/lib/inch/cli/command_parser.rb:62:in `run'
	from /home/rene/projects/inch/lib/inch/cli/command_parser.rb:52:in `run'
	from /home/rene/projects/inch/bin/inch:23:in `<top (required)>'
	from /home/rene/.rvm/gems/ruby-2.1.6@inch/bin/inch:23:in `load'
	from /home/rene/.rvm/gems/ruby-2.1.6@inch/bin/inch:23:in `<main>'
	from /home/rene/.rvm/gems/ruby-2.1.6@inch/bin/ruby_executable_hooks:15:in `eval'
	from /home/rene/.rvm/gems/ruby-2.1.6@inch/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jashank** [comment]
Yup. `rake test` spewed dozens of screens of angry errors and crashed before reporting that tests failed... but running `inch` in-tree works fine and produces (apparently) sensible output?

**Comment by rrrene** [comment]
Not when run on Ruby itself (that's what the stacktrace above is from). I will have to find some time to fix, unless somebody else wants to dive into it and submit a PR.

**Comment by Jesterovskiy** [comment]
This is I get from github dependency graph:
The yard dependency defined in Gemfile.lock has a known high severity security vulnerability in version range < 0.9.11 and should be updated. https://nvd.nist.gov/vuln/detail/CVE-2017-17042
Gemfile.lock update suggested:
yard ~> 0.9.11

**Comment by smileart** [comment]
Yep. Need to update my gems which use `yard`, due to security issue @Jesterovskiy mentioned above, but can't cause `yard` needs to be updated first.

```sh
Bundler could not find compatible versions for gem "yard":
  In Gemfile:
    yard (~> 0.9.12)

    inch (~> 0.7) was resolved to 0.7.1, which depends on
      yard (~> 0.8.7.5)
```

**Comment by smileart** [comment]
Anyone? 👋

It seems that @rrrene (hope he's O.K. 😞) abandoned the project, at least for now, since there also lots and lots of unresolved issues on [inch_ci-web](https://github.com/inch-ci/inch_ci-web) and the [site](https://inch-ci.org) itself doesn't work properly anymore.

**Comment by michaelherold** [comment]
I've been trying to make progress on this, but it is difficult because the test suite isn't passing. I have a small PR that makes some progress on the test suite, but still need to keep digging.

**Comment by leoarnold** [comment]
@smileart Don't worry, @rrrene is good, he was just very very busy throughout 2017: http://trivelop.de/2018/01/01/looking-back/

**Comment by rrrene** [comment]
@michaelherold I merged your PR and updated YARD to `~> 0.9.12`. There are less tests failing than with previous `0.9.x` versions of YARD, but we still have to fix at least the `rake test:ruby` ones before publishing the next "real" release of Inch (you can, of course, point your installations to use `rrrene/inch` in the meantime).

@jashank @Jesterovskiy @smileart Sorry, for not being more responsive on this. I am trying to maintain my OSS projects as best I can, but my available open-source-time is decreasing gradually over the last 1.5 years. Inch is often neglected in terms of "time spent on it", since I no longer use Ruby professionally (this is not meant as an excuse but rather an explanation). 

I am really dependent on contributions here, which is why I am super grateful to @michaelherold and anybody else who chose to spend time on this.

@leoarnold I am not sure what you are adding to the conversation here. As with previous written communications between us, I get the distinct impression that you are either (a) really, really bad at communicating with humans or (b) one of those trolls who really like to *use* and *complain about* open source software, but really dislike actually *contributing* something back.

**Comment by rrrene** [comment]
For the record (since I believe in admitting one's errors): @leoarnold and I had a chat via email and it now really seems like a case of "lost in translation" (I won't edit the comment above, so this comment makes sense).

On the subject at hand: I hope we can get Inch to a state where we can release a pre-version for `v0.8.0` and continue work from there. :+1: Volunteers are very welcome!

Inch was my first somewhat original Open Source project and I would very much like for it to live on.

**Comment by michaelherold** [comment]
@rrrene I would find it helpful to see some documentation about Inch interacts with YARD. I think it would be a good use of your limited time to explain the architecture behind the gem. As with most things that introspect other programs, it's a difficult piece of code to dig into without any prior knowledge.

I'll see what I can do to get the test suite closer to passing. I think a good first step might be to fix all of the warnings that pop up while running the suite.

Thanks for your work in writing and maintaining Inch over the years - it's a great tool. I hope we can round up a community to help you maintain it!

**Comment by rrrene** [comment]
Thanks to @michaelherold's efforts, Inch `0.8.0.rc1` is now on RubyGems. :+1:

**Comment by mensfeld** [comment]
Guys any chance on this one? Would love to be able to use inch but it locks the yard dependency to a really old version :(

**Comment by mensfeld** [comment]
@rrrene I tested it. There's nothing wrong. It's just the fact that it is a beta and due to the way we upgrade gems automatically, locking to a beta (which is required in the gems file) will cause it to stop being upgraded.

**Comment by rrrene** [comment]
@mensfeld :+1: Here you go: https://rubygems.org/gems/inch/versions/0.8.0
